corrigingo commando /proximos
garoa/ChuviscoBot pull request #89
Opened 2019-08-22 12:21 UTC by edinhodiluviano

(issue #86)

2019-08-24 23:33 UTC, felipesanches commented on agenda_test.py
> +   {"dia_da_semana": "Quinta",
Não faz nenhum sentido trocar `Sábado` por `Quinta` nesse teste. Desfaça isso e garanta que o código passa em todos testes.

2019-08-24 23:34 UTC, felipesanches requested changes
**"Desquebre"** o teste de código `"Sábado, 12/MAR/2020 a partir das 16:00"`

2019-08-24 23:36 UTC, felipesanches commented
Temos também alguns alertas do linter no Travis build aqui: https://travis-ci.org/garoa/ChuviscoBot/builds/575310700

![Screenshot at 2019-08-24 20:35:53](https://user-images.githubusercontent.com/213676/63643774-03249a00-c6c8-11e9-9644-04b1e8795a21.png)

2019-08-25 02:57 UTC, edinhodiluviano commented
Sobre o teste, dia 12/mar/2020 é uma quinta. Posso trocar o dia, no texto, para quinta ou a data para 14. Qual dos dois fica melhor?

Corrigido o duplo import acusado pelo pylint.
Vou esperar resolver o teste pra n ficar mandando varios commits : )

2023-06-16 01:31 UTC, closed without merging